use_frameworks!

platform :ios, '8.0'

target 'RBSFiveStarRating_Example' do
  pod 'RBSFiveStarRating', :path => '../'

  target 'RBSFiveStarRating_Tests' do
    inherit! :search_paths

    
  end
end
